project_id = "isxdedybwhlxzeuymxcq"

[functions.generate-outline]
verify_jwt = false

[functions.generate-blocks]
verify_jwt = false

[functions.refine-block]
verify_jwt = false

[functions.generate-block-content]
verify_jwt = false
