import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

type ImageSource = "stock" | "web" | "illustration" | "gif" | "ai";

interface ImageResult {
  thumbUrl: string;
  url: string;
  credit?: string;
  license?: string;
  provider: string;
}

async function searchPexels(q: string, apiKey: string, perPage = 12): Promise<ImageResult[]> {
  const res = await fetch(
    `https://api.pexels.com/v1/search?query=${encodeURIComponent(q)}&per_page=${perPage}&orientation=landscape`,
    { headers: { Authorization: apiKey } }
  );
  if (!res.ok) return [];
  const data = await res.json();
  return (data.photos ?? []).map((p: Record<string, unknown>) => {
    const src = p.src as Record<string, string>;
    return {
      thumbUrl: src.medium,
      url: src.large2x || src.large || src.original,
      credit: `Photo by ${p.photographer} on Pexels`,
      license: "Pexels License",
      provider: "pexels",
    };
  });
}

async function searchIllustrations(q: string, apiKey: string): Promise<ImageResult[]> {
  // Search Pexels with illustration-friendly terms
  const res = await fetch(
    `https://api.pexels.com/v1/search?query=${encodeURIComponent(q + " illustration minimal flat")}&per_page=12&orientation=landscape`,
    { headers: { Authorization: apiKey } }
  );
  if (!res.ok) return [];
  const data = await res.json();
  return (data.photos ?? []).map((p: Record<string, unknown>) => {
    const src = p.src as Record<string, string>;
    return {
      thumbUrl: src.medium,
      url: src.large2x || src.large || src.original,
      credit: `Photo by ${p.photographer} on Pexels`,
      license: "Pexels License",
      provider: "pexels-illustration",
    };
  });
}

async function searchGifs(q: string): Promise<ImageResult[]> {
  // Use Giphy public beta key as fallback
  const GIPHY_KEY = "dc6zaTOxFJmzC"; // public beta key
  const res = await fetch(
    `https://api.giphy.com/v1/gifs/search?api_key=${GIPHY_KEY}&q=${encodeURIComponent(q)}&limit=12&rating=g`
  );
  if (!res.ok) return [];
  const data = await res.json();
  return (data.data ?? []).map((g: Record<string, unknown>) => {
    const images = g.images as Record<string, Record<string, string>>;
    return {
      thumbUrl: images.fixed_height_small?.url || images.fixed_width?.url,
      url: images.original?.url || images.downsized?.url,
      credit: "via Giphy",
      license: "Giphy License",
      provider: "giphy",
    };
  }).filter((r: ImageResult) => r.thumbUrl && r.url);
}

async function generateAIImages(q: string, lovableKey: string): Promise<ImageResult[]> {
  // Generate a single AI image
  const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${lovableKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash-image",
      messages: [
        {
          role: "user",
          content: `Generate a professional, high-quality image for a business presentation slide: ${q}. Clean corporate style, ultra high resolution.`,
        },
      ],
      modalities: ["image", "text"],
    }),
  });

  if (!res.ok) return [];
  const data = await res.json();
  const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!imageUrl) return [];

  return [{
    thumbUrl: imageUrl,
    url: imageUrl,
    credit: "Generated by AI",
    license: "AI Generated",
    provider: "ai",
  }];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  // Auth check
  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
  const _authClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!);
  const { data: { user: _authUser }, error: _authError } = await _authClient.auth.getUser(authHeader.replace("Bearer ", ""));
  if (_authError || !_authUser) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  try {
    const { q, source = "stock" } = await req.json() as { q: string; source?: ImageSource };

    if (!q || typeof q !== "string" || q.trim().length === 0) {
      return new Response(
        JSON.stringify({ error: "Query q is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const PEXELS_API_KEY = Deno.env.get("PEXELS_API_KEY");
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");

    let results: ImageResult[] = [];

    if (source === "stock" || source === "web") {
      if (PEXELS_API_KEY) {
        results = await searchPexels(q.trim(), PEXELS_API_KEY);
      }
    } else if (source === "illustration") {
      if (PEXELS_API_KEY) {
        results = await searchIllustrations(q.trim(), PEXELS_API_KEY);
      }
    } else if (source === "gif") {
      results = await searchGifs(q.trim());
    } else if (source === "ai") {
      if (LOVABLE_API_KEY) {
        results = await generateAIImages(q.trim(), LOVABLE_API_KEY);
      }
    }

    return new Response(
      JSON.stringify({ results }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("image-search error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
