import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface ImageBlock {
  blockIndex: number;
  query: string;
  alt: string;
  caption?: string;
  aspect?: string;
}

interface ResolvedImage {
  blockIndex: number;
  src: string;
  alt: string;
  query: string;
  provider: string;
  credit?: string;
  caption?: string;
  aspect: string;
}

interface RequestBody {
  images: ImageBlock[];
  mode: "none" | "stock" | "ai" | "hybrid";
  projectId?: string;
}

async function searchPexels(query: string, apiKey: string): Promise<{ src: string; credit: string } | null> {
  try {
    const response = await fetch(
      `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=1&orientation=landscape`,
      {
        headers: {
          Authorization: apiKey,
        },
      }
    );

    if (!response.ok) {
      console.error("Pexels API error:", response.status);
      return null;
    }

    const data = await response.json();
    
    if (data.photos && data.photos.length > 0) {
      const photo = data.photos[0];
      return {
        src: photo.src.large2x || photo.src.large || photo.src.medium,
        credit: `Photo by ${photo.photographer} on Pexels`,
      };
    }
    
    return null;
  } catch (error) {
    console.error("Pexels fetch error:", error);
    return null;
  }
}

async function generateAIImage(query: string, apiKey: string): Promise<{ src: string; credit: string } | null> {
  try {
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [
          {
            role: "user",
            content: `Generate a professional, high-quality image for a business presentation: ${query}. Ultra high resolution, clean corporate style.`,
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      console.error("AI image generation error:", response.status);
      return null;
    }

    const data = await response.json();
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (imageUrl) {
      return {
        src: imageUrl,
        credit: "Generated by AI",
      };
    }

    return null;
  } catch (error) {
    console.error("AI image generation error:", error);
    return null;
  }
}

serve(async (req) => {
  const requestId = crypto.randomUUID().slice(0, 8);
  console.log(`[${requestId}] resolve-images request`);

  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  // Auth check
  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
  const _authClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!);
  const { data: { user: _authUser }, error: _authError } = await _authClient.auth.getUser(authHeader.replace("Bearer ", ""));
  if (_authError || !_authUser) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  try {
    const body = (await req.json()) as RequestBody;
    const { images, mode, projectId } = body;

    if (!images || !Array.isArray(images)) {
      return new Response(
        JSON.stringify({ error: "images array is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (mode === "none") {
      // Return placeholder images
      const resolved: ResolvedImage[] = images.map((img) => ({
        blockIndex: img.blockIndex,
        src: `https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=800&fit=crop`,
        alt: img.alt,
        query: img.query,
        provider: "placeholder",
        caption: img.caption,
        aspect: img.aspect || "16:9",
      }));

      return new Response(
        JSON.stringify({ images: resolved, requestId }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const PEXELS_API_KEY = Deno.env.get("PEXELS_API_KEY");
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Missing Supabase configuration");
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    const resolved: ResolvedImage[] = [];

    for (const img of images) {
      const cacheKey = img.query.toLowerCase().trim();
      const provider = mode === "ai" ? "ai" : "pexels";

      // Check cache first
      const { data: cached } = await supabase
        .from("image_cache")
        .select("*")
        .eq("query", cacheKey)
        .eq("provider", provider)
        .maybeSingle();

      if (cached) {
        console.log(`[${requestId}] Cache hit for query: ${cacheKey}`);
        resolved.push({
          blockIndex: img.blockIndex,
          src: cached.src,
          alt: img.alt,
          query: img.query,
          provider: cached.provider,
          credit: cached.credit,
          caption: img.caption,
          aspect: img.aspect || cached.aspect || "16:9",
        });
        continue;
      }

      let result: { src: string; credit: string } | null = null;

      if (mode === "stock" || mode === "hybrid") {
        if (PEXELS_API_KEY) {
          result = await searchPexels(img.query, PEXELS_API_KEY);
        }
      }

      if (!result && (mode === "ai" || mode === "hybrid")) {
        if (LOVABLE_API_KEY) {
          result = await generateAIImage(img.query, LOVABLE_API_KEY);
        }
      }

      if (result) {
        // Cache the result
        await supabase.from("image_cache").upsert({
          query: cacheKey,
          provider: mode === "ai" ? "ai" : "pexels",
          src: result.src,
          alt: img.alt,
          credit: result.credit,
          aspect: img.aspect || "16:9",
        }, { onConflict: "query,provider" });

        resolved.push({
          blockIndex: img.blockIndex,
          src: result.src,
          alt: img.alt,
          query: img.query,
          provider: mode === "ai" ? "ai" : "pexels",
          credit: result.credit,
          caption: img.caption,
          aspect: img.aspect || "16:9",
        });
      } else {
        // Fallback placeholder
        resolved.push({
          blockIndex: img.blockIndex,
          src: `https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=800&fit=crop`,
          alt: img.alt,
          query: img.query,
          provider: "placeholder",
          caption: img.caption,
          aspect: img.aspect || "16:9",
        });
      }
    }

    // Store assets if projectId provided
    if (projectId) {
      const assets = resolved.map((img) => ({
        project_id: projectId,
        src: img.src,
        alt: img.alt,
        query: img.query,
        provider: img.provider,
        credit: img.credit,
        aspect: img.aspect,
      }));

      await supabase.from("assets").insert(assets);
    }

    console.log(`[${requestId}] Resolved ${resolved.length} images`);

    return new Response(
      JSON.stringify({ images: resolved, requestId }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error(`[${requestId}] Error:`, error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
